#!/usr/bin/env bash
# bootstrap_stage0a.sh — minimal node bring-up for Stage 0a only.
#
# Stage 0a is a CPU+TCP+DRAM transport bench between two nodes. We don't
# need vLLM, models, or even CUDA. This script ONLY does what's needed to
# produce a working transfer_engine_lat_bench binary and open the wire.
#
# Idempotent. Safe to re-run. Per-step skip-if-done checks.
#
# Required env (or args):
#   PRFAAS_WORK_DIR     where to clone + build (e.g. /scratch/prfaas)
#   PEER_PUBLIC_IP      IP of the other side, for firewall scoping
#   PRFAAS_ROLE         x_gateway|y  (informational)
#
# Optional:
#   MOONCAKE_REPO       default https://github.com/HarshavardhanK/Mooncake.git
#   MOONCAKE_BRANCH     default feat/prfaas-m1.5-vllm-baseline
#   PORT_LO/PORT_HI     firewall range, default 13000/17000
#                       (covers Mooncake P2P RPC range 15000-17000 + extra)
#
# Side effects:
#   - apt-get install (sudo)
#   - mkdir -p $PRFAAS_WORK_DIR
#   - git clone $MOONCAKE_REPO -> $PRFAAS_WORK_DIR/Mooncake
#   - sudo $PRFAAS_WORK_DIR/Mooncake/dependencies.sh -y
#   - native build into $PRFAAS_WORK_DIR/Mooncake/build
#   - sudo host_tune.sh (sysctls)
#   - sudo iptables: open PORT_LO-PORT_HI from PEER_PUBLIC_IP only
#   - writes $PRFAAS_WORK_DIR/.prfaas_stage0a_env

set -euo pipefail

: "${PRFAAS_WORK_DIR:?PRFAAS_WORK_DIR required}"
: "${PEER_PUBLIC_IP:?PEER_PUBLIC_IP required}"
: "${PRFAAS_ROLE:?PRFAAS_ROLE required (x_gateway|y)}"
: "${MOONCAKE_REPO:=https://github.com/HarshavardhanK/Mooncake.git}"
: "${MOONCAKE_BRANCH:=feat/prfaas-m1.5-vllm-baseline}"
: "${PORT_LO:=13000}"
: "${PORT_HI:=17000}"

log() { printf '[bootstrap_stage0a %s] %s\n' "$(date -u +%H:%M:%S)" "$*" >&2; }
die() { printf '[bootstrap_stage0a FATAL] %s\n' "$*" >&2; exit 1; }

if ! command -v sudo >/dev/null; then die "sudo required"; fi
if ! sudo -n true 2>/dev/null; then die "sudo NOPASSWD required"; fi

# ---- 0. workdir ----------------------------------------------------------
log "ensuring work dir ${PRFAAS_WORK_DIR}"
sudo mkdir -p "${PRFAAS_WORK_DIR}"
sudo chown -R "$(id -u):$(id -g)" "${PRFAAS_WORK_DIR}"
mkdir -p "${PRFAAS_WORK_DIR}/logs"

# ---- 1. clone / pull -----------------------------------------------------
repo_dir="${PRFAAS_WORK_DIR}/Mooncake"
if [[ ! -d "${repo_dir}/.git" ]]; then
  log "cloning ${MOONCAKE_REPO} -> ${repo_dir}"
  git clone --recursive --branch "${MOONCAKE_BRANCH}" "${MOONCAKE_REPO}" "${repo_dir}"
else
  log "repo exists; fetching + checking out ${MOONCAKE_BRANCH}"
  git -C "${repo_dir}" fetch origin "${MOONCAKE_BRANCH}"
  git -C "${repo_dir}" checkout "${MOONCAKE_BRANCH}"
  git -C "${repo_dir}" pull --ff-only
  git -C "${repo_dir}" submodule update --init --recursive
fi

# ---- 2. system deps + yalantinglibs (Mooncake's own installer) -----------
if [[ ! -d /usr/local/include/ylt ]]; then
  log "running sudo dependencies.sh -y (apt + yalantinglibs)"
  ( cd "${repo_dir}" && sudo bash dependencies.sh -y ) \
    > "${PRFAAS_WORK_DIR}/logs/dependencies.log" 2>&1 \
    || { tail -50 "${PRFAAS_WORK_DIR}/logs/dependencies.log" >&2; die "dependencies.sh failed"; }
else
  log "skip dependencies.sh (yalantinglibs already in /usr/local/include/ylt)"
fi

# ---- 3. native build of transfer_engine_lat_bench ------------------------
bench_bin="${repo_dir}/build/prfaas/m1-tcp-bench/bench/transfer_engine_lat_bench"
if [[ ! -x "${bench_bin}" ]]; then
  log "native_build.sh"
  ( cd "${repo_dir}" \
      && BUILD_DIR="${repo_dir}/build" \
         bash prfaas/m1-tcp-bench/scripts/native_build.sh ) \
    > "${PRFAAS_WORK_DIR}/logs/native_build.log" 2>&1 \
    || { tail -80 "${PRFAAS_WORK_DIR}/logs/native_build.log" >&2; die "native_build.sh failed"; }
else
  log "skip native_build (binary present)"
fi

[[ -x "${bench_bin}" ]] || die "expected ${bench_bin} after build, missing"

# Make the bench discoverable on PATH for this shell + future SSH sessions.
prfaas_env="${PRFAAS_WORK_DIR}/.prfaas_stage0a_env"
cat > "${prfaas_env}" <<EOF
# auto-generated by bootstrap_stage0a.sh on $(date -u +%FT%TZ)
export PRFAAS_ROLE="${PRFAAS_ROLE}"
export PRFAAS_WORK_DIR="${PRFAAS_WORK_DIR}"
export PEER_PUBLIC_IP="${PEER_PUBLIC_IP}"
export MOONCAKE_DIR="${repo_dir}"
export MOONCAKE_BUILD_DIR="${repo_dir}/build"
export PATH="${repo_dir}/build/prfaas/m1-tcp-bench/bench:${repo_dir}/build/mooncake-transfer-engine/example:\${PATH}"
export LD_LIBRARY_PATH="${repo_dir}/build/mooncake-transfer-engine/src:${repo_dir}/build/mooncake-asio:\${LD_LIBRARY_PATH:-}"
EOF
log "wrote env to ${prfaas_env}"

# ---- 4. host TCP tuning --------------------------------------------------
log "applying host TCP tuning (sudo)"
sudo bash "${repo_dir}/prfaas/m1-tcp-bench/scripts/host_tune.sh" \
  > "${PRFAAS_WORK_DIR}/logs/host_tune.log" 2>&1 \
  || { tail -30 "${PRFAAS_WORK_DIR}/logs/host_tune.log" >&2; log "host_tune.sh exited non-zero (continuing)"; }

# ---- 5. firewall: open PORT_LO-PORT_HI from PEER_PUBLIC_IP ---------------
# Idempotent: only insert if no matching rule exists.
fw_rule="-p tcp -s ${PEER_PUBLIC_IP} --dport ${PORT_LO}:${PORT_HI} -j ACCEPT"
fw_comment="prfaas-stage0a-from-${PEER_PUBLIC_IP}"
# shellcheck disable=SC2086
if ! sudo iptables -C INPUT $fw_rule -m comment --comment "${fw_comment}" 2>/dev/null; then
  log "iptables: opening ${PORT_LO}-${PORT_HI}/tcp from ${PEER_PUBLIC_IP}"
  # shellcheck disable=SC2086
  sudo iptables -I INPUT 1 $fw_rule -m comment --comment "${fw_comment}"
else
  log "iptables: rule already present (${fw_comment})"
fi

# ---- 6. summary ----------------------------------------------------------
log "DONE. Bench binary: ${bench_bin}"
log "Source the env in subsequent shells:  . ${prfaas_env}"
log "Then on the target side: run_target.sh; on the initiator: run_initiator.sh"
