#!/usr/bin/env python3
"""
Walk a results directory, compute Λ_max(SLO) per (config, workload, time),
and emit a SUMMARY.md with the headline ratio + plots.

Also supports `--decide-model` mode: read a Stage 0 transport bench results
dir and emit MODEL_DECISION.md per the SIZING.md decision tree.

Schemas this consumes:
  - Per-cell vLLM benchmark JSON (whatever benchmark_serving.py writes)
  - Per-workload sweep.csv produced by run_concurrency_sweep.sh
  - Per-stage layout: <results_dir>/<config>/<workload>/sweep.csv
"""
from __future__ import annotations

import argparse
import csv
import json
import os
import sys
from collections import defaultdict
from pathlib import Path
from statistics import median


def lambda_max_from_sweep(sweep_csv: Path) -> tuple[float | None, float | None]:
    """Return (Λ_max in QPS, ttft_p95_at_lambda_max) for the highest concurrency
    that meets the SLO. QPS is approximated as `concurrency / (e2el_p50_ms / 1000)`
    — same as `concurrency / mean_request_latency`."""
    if not sweep_csv.exists():
        return None, None
    rows = list(csv.DictReader(sweep_csv.open()))
    feasible = [r for r in rows if str(r.get("slo_met")) == "1"]
    if not feasible:
        return None, None
    # Highest concurrency among feasible cells.
    best = max(feasible, key=lambda r: int(r["concurrency"]))
    conc = int(best["concurrency"])
    e2el_ms = float(best["e2el_p50_ms"]) if best["e2el_p50_ms"] else None
    if not e2el_ms or e2el_ms <= 0:
        return None, None
    qps = conc / (e2el_ms / 1000.0)
    return qps, float(best["ttft_p95_ms"])


def cmd_summarize(stage_dir: Path, out_md: Path) -> None:
    # Layout: stage_dir / <config> / <workload> / sweep.csv
    table: dict[tuple[str, str], tuple[float | None, float | None]] = {}
    configs = sorted(p.name for p in stage_dir.iterdir() if p.is_dir())
    workloads_seen: set[str] = set()
    for config in configs:
        cdir = stage_dir / config
        for wdir in sorted(cdir.iterdir()) if cdir.is_dir() else []:
            if not wdir.is_dir():
                continue
            sweep = wdir / "sweep.csv"
            qps, p95 = lambda_max_from_sweep(sweep)
            table[(config, wdir.name)] = (qps, p95)
            workloads_seen.add(wdir.name)

    with out_md.open("w") as f:
        f.write(f"# {stage_dir.name} — Λ_max(SLO) summary\n\n")
        f.write("Generated by `extract_lambda_max.py`. Λ_max is the highest "
                "concurrency cell that met TTFT P95 ≤ SLO, converted to QPS via "
                "`concurrency / E2EL_P50`.\n\n")
        f.write("## Per-config Λ_max (QPS)\n\n")
        f.write("| Workload | " + " | ".join(configs) + " |\n")
        f.write("|" + "|".join(["---"] * (len(configs) + 1)) + "|\n")
        for w in sorted(workloads_seen):
            row = [f"`{w}`"]
            for c in configs:
                qps, _ = table.get((c, w), (None, None))
                row.append(f"{qps:.2f}" if qps is not None else "—")
            f.write("| " + " | ".join(row) + " |\n")
        f.write("\n## Headline ratios\n\n")
        # If we have a Config H baseline, emit (P/H) and (N/H) per workload.
        if "configH" in configs:
            f.write("| Workload | Λ_max(P) / Λ_max(H) | Λ_max(N) / Λ_max(H) |\n")
            f.write("|---|---|---|\n")
            for w in sorted(workloads_seen):
                h_qps, _ = table.get(("configH", w), (None, None))
                p_qps, _ = table.get(("configP", w), (None, None))
                n_qps, _ = table.get(("configN", w), (None, None))
                ph = f"{p_qps/h_qps:.2f}" if (p_qps and h_qps) else "—"
                nh = f"{n_qps/h_qps:.2f}" if (n_qps and h_qps) else "—"
                f.write(f"| `{w}` | {ph} | {nh} |\n")
        else:
            f.write("(no `configH` baseline found in this stage)\n")
    print(f"wrote {out_md}")


def cmd_decide_model(stage0_dir: Path, out_md: Path) -> None:
    # Walk all sub-dirs that look like timestamped runs; pull goodput_gbps
    # from each results.csv; take the median.
    goodputs: list[float] = []
    for sub in stage0_dir.rglob("results.csv"):
        for row in csv.DictReader(sub.open()):
            v = row.get("goodput_gbps") or row.get("goodput_Gbps")
            try:
                if v:
                    goodputs.append(float(v))
            except ValueError:
                pass
    if not goodputs:
        print("ERROR: no goodput_gbps found anywhere under", stage0_dir, file=sys.stderr)
        sys.exit(2)
    med = median(goodputs)
    lo, hi = min(goodputs), max(goodputs)

    # Decision tree (matches SIZING.md §4)
    if med >= 25:
        primary = "Qwen/Qwen3-Next-80B-A3B-Instruct"
        target = int(med * 1e9 / 8 / 24576)
        rationale = ("≥ 25 Gbps median multi-flow goodput — Qwen3-Next-80B-A3B "
                     "fits at full prefill load.")
    elif med >= 10:
        primary = "nvidia/NVIDIA-Nemotron-Nano-9B-v2"
        target = int(med * 1e9 / 8 / 16384 / 2)
        rationale = ("10–25 Gbps median goodput — Nemotron-Nano with two "
                     "prefill replicas at half-wire each.")
    elif med >= 5:
        primary = "nvidia/NVIDIA-Nemotron-Nano-9B-v2"
        target = int(med * 1e9 / 8 / 16384)
        rationale = ("5–10 Gbps median goodput — single Nemotron-Nano "
                     "prefiller; report as low-bandwidth-WAN study.")
    else:
        primary = "nvidia/NVIDIA-Nemotron-Nano-9B-v2"
        target = int(med * 1e9 / 8 / 16384)
        rationale = ("< 5 Gbps median goodput — below paper's feasibility "
                     "envelope; run as breakeven characterization.")

    out_md.parent.mkdir(parents=True, exist_ok=True)
    with out_md.open("w") as f:
        f.write("# Stage 0 model decision\n\n")
        f.write(f"- Measured wire goodput: median **{med:.2f} Gbps** "
                f"(min {lo:.2f}, max {hi:.2f}) across {len(goodputs)} cells.\n")
        f.write(f"- Decision: **PRIMARY_MODEL = {primary}**\n")
        f.write(f"- Target sustained prefill throughput: ~{target:,} input-tokens/sec.\n")
        f.write(f"- Rationale: {rationale}\n\n")
        f.write("Append to `~/.prfaas_env`:\n\n```bash\n")
        f.write(f"export PRIMARY_MODEL={primary}\n")
        f.write(f"export PRIMARY_MODEL_TAG={primary.replace('/', '_')}\n")
        f.write("```\n")
    print(f"wrote {out_md}")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--decide-model", action="store_true")
    p.add_argument("--stage0-results", type=Path)
    p.add_argument("--stage", type=str, help="e.g. stageB, stageD")
    p.add_argument("--results-dir", type=Path)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()

    if args.decide_model:
        if not args.stage0_results:
            p.error("--decide-model needs --stage0-results")
        cmd_decide_model(args.stage0_results, args.out)
        return

    if not args.results_dir:
        p.error("--results-dir is required for summarize mode")
    cmd_summarize(args.results_dir, args.out)


if __name__ == "__main__":
    main()
