#!/usr/bin/env bash
# Bring a single node to a state where it can participate in M1.5.
#
# Idempotent — safe to re-run. Per-step "skip if done" checks.
#
# Steps:
#   1. apt packages (sudo) — same list as Mooncake's dependencies.sh
#   2. python virtualenv at $PRFAAS_VENV with vLLM + benchmark deps
#   3. native build of transfer_engine_bench + transfer_engine_lat_bench
#      (reuses prfaas/m1-tcp-bench/scripts/native_build.sh)
#   4. fetch model weights into the role-appropriate dir
#   5. host TCP tuning via prfaas/m1-tcp-bench/scripts/host_tune.sh
#   6. write a sample ~/.prfaas_env if one doesn't already exist
#
# Usage:
#   bash prfaas/m1.5-vllm-baseline/scripts/node_setup.sh {smoke|primary|both}

set -euo pipefail

# shellcheck source=lib/common.sh
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

WHICH_MODEL="${1:-smoke}"
case "${WHICH_MODEL}" in
  smoke|primary|both) ;;
  *) m15_die "usage: $0 {smoke|primary|both}" ;;
esac

# ---- 1. system packages ---------------------------------------------------
if [[ -f /etc/debian_version ]]; then
  m15_log "installing system packages via apt (will sudo)"
  sudo apt-get update -qq
  sudo apt-get install -y --no-install-recommends \
    build-essential cmake ninja-build pkg-config \
    libgoogle-glog-dev libgflags-dev libnuma-dev libssl-dev \
    libcurl4-openssl-dev libgrpc++-dev libprotobuf-dev protobuf-compiler-grpc \
    libboost-all-dev libhiredis-dev libjsoncpp-dev \
    python3 python3-venv python3-pip \
    git curl wget ca-certificates iproute2 iptables iputils-ping \
    iperf3 socat tracepath net-tools >/dev/null
fi

# ---- 2. python venv -------------------------------------------------------
if [[ ! -d "${PRFAAS_VENV}" ]]; then
  m15_log "creating python venv at ${PRFAAS_VENV}"
  python3 -m venv "${PRFAAS_VENV}"
fi
# shellcheck disable=SC1091
source "${PRFAAS_VENV}/bin/activate"
pip install -q --upgrade pip
# vLLM version pin is intentionally absent here — we resolve it during Stage A
# (see EXPERIMENT_PLAN §10 Q3). For now install the latest, which has both v0
# and v1 connector paths reachable.
pip install -q --upgrade vllm
pip install -q quart httpx aiohttp pandas datasets matplotlib uvicorn fastapi requests
pip install -q "huggingface_hub[cli]"

# ---- 3. native build of M1 benches ---------------------------------------
if [[ ! -x "${REPO_ROOT}/build/mooncake-transfer-engine/example/transfer_engine_bench" ]]; then
  m15_log "running native_build.sh (Mooncake submodules + cmake)"
  if [[ ! -f "${REPO_ROOT}/extern/yalantinglibs/CMakeLists.txt" ]]; then
    git -C "${REPO_ROOT}" submodule update --init --recursive
  fi
  ( cd "${REPO_ROOT}" && \
    if [[ ! -f /usr/local/include/ylt/CMakeLists.txt ]]; then
      sudo bash dependencies.sh -y
    fi
    bash prfaas/m1-tcp-bench/scripts/native_build.sh
  )
fi

# ---- 4. fetch model weights ----------------------------------------------
case "${PRFAAS_ROLE:-}" in
  x_*) model_dir="${X_MODEL_DIR}" ;;
  y)   model_dir="${Y_MODEL_DIR}" ;;
  *)   model_dir="${HOME}/models" ;;
esac
mkdir -p "${model_dir}"

stage_model() {
  local hf_id="$1"
  local target
  target="${model_dir}/$(echo "${hf_id}" | tr '/' '_')"
  if [[ -d "${target}" && -n "$(ls -A "${target}" 2>/dev/null)" ]]; then
    m15_log "model already staged: ${target}"
    return
  fi
  m15_log "downloading ${hf_id} -> ${target}"
  huggingface-cli download "${hf_id}" --local-dir "${target}"
}

case "${WHICH_MODEL}" in
  smoke)   stage_model "${SMOKE_MODEL}" ;;
  primary) stage_model "${PRIMARY_MODEL}" ;;
  both)    stage_model "${SMOKE_MODEL}"; stage_model "${PRIMARY_MODEL}" ;;
esac

# ---- 5. host TCP tuning --------------------------------------------------
if [[ -x "${REPO_ROOT}/prfaas/m1-tcp-bench/scripts/host_tune.sh" ]]; then
  m15_log "applying host TCP tuning (sudo)"
  sudo "${REPO_ROOT}/prfaas/m1-tcp-bench/scripts/host_tune.sh"
fi

# ---- 6. .prfaas_env stub --------------------------------------------------
if [[ ! -f "${HOME}/.prfaas_env" ]]; then
  m15_log "writing stub ~/.prfaas_env (PLEASE EDIT before running stages)"
  cat > "${HOME}/.prfaas_env" <<EOF
# Auto-generated by node_setup.sh. PLEASE EDIT THIS FILE.
# See prfaas/m1.5-vllm-baseline/PREFLIGHT.md for the schema.

export PRFAAS_ROLE=__SET_ME__            # x_gateway | x_internal | y
export PRFAAS_NODE_INDEX=0

export X_GATEWAY_PUBLIC_IP=__SET_ME__
export X_GATEWAY_INTERNAL_IP=__SET_ME__
export X_INTERNAL_PUBLIC_IP=
export X_INTERNAL_INTERNAL_IP=__SET_ME__
export Y_PUBLIC_IP=__SET_ME__

export MOONCAKE_MASTER_HOST=\$X_GATEWAY_PUBLIC_IP
export MOONCAKE_MASTER_PORT=10001
export ETCD_HOST=\$X_GATEWAY_PUBLIC_IP
export ETCD_PORT=2379
export MOONCAKE_TRANSPORT_PORT_RANGE=13000-13999

export X_MODEL_DIR=${X_MODEL_DIR:-/mnt/vast/models}
export Y_MODEL_DIR=${Y_MODEL_DIR:-/scratch/models}

export SMOKE_MODEL=${SMOKE_MODEL}
export PRIMARY_MODEL=${PRIMARY_MODEL}

export TTFT_SLO_LONG_CONTEXT_MS=2000
export TTFT_SLO_CHAT_BALANCED_MS=1000
export TTFT_SLO_RAG_SUMMARY_MS=1500
export TTFT_SLO_CODE_COMPLETE_MS=1500
EOF
fi

m15_log "node_setup OK — next: edit ~/.prfaas_env, then run preflight_check.sh"
